### ISSUE TITLE
USER STORY: VIEW AN EVENTS PAGE

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#10]
Epic #3

As a **user** I can **view an events page** so that **I can see a list of events**.

### Acceptance Criteria: 

* An events page is displayed at /events, showing a list of events

### Tasks:

- [x] Add events page to urls.py
- [x] Create events template
- [x] View events page
- [x] See list of events on page
---
