### ISSUE TITLE
USER STORY: VIEW EVENT DETAILS

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#11]
Epic #3 

As a **user** I can **click a link on the events page** so that **I can see the details of the individual event on a new page**.

### Acceptance Criteria: 

* The events list page will have links for each event which take the user to a new page where the full details are displayed.

### Tasks:

- [x] Create new template for event details
- [x] Create links on the events page
- [x] Add url path
- [x] Add event details view
---
