### ISSUE TITLE
USER STORY: SITE PAGINATION

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#13]
Epic: #3 

As a **user** I can **see a paginated list of events** so that **I can view a few posts at a time**.

### Acceptance Criteria: 

* The events page paginates when the number of events exceeds six.

### Tasks:

- [x] Add pagination to events view
- [x] Add add_pagination code to events.html
- [x] Add a total of seven posts to confirm
---
