### ISSUE TITLE
USER STORY: VIEW ATTENDEE NUMBER

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#16]
Epic: #3 

As a **user** I can **see the total number of attendees for an event** so that **I can see how many people are attending**.

### Acceptance Criteria: 

* Attendee number displays on Event Details page and updates when additional attendees are added in the admin panel.

### Tasks:

- [x] Add {{ event.number_of_attendees }} to event_details template
- [x] Check that number of attendees displays on event details page
- [x] Adjust number of attendees to check that number updates on event details page
---
