### ISSUE TITLE
USER STORY: USER ACCOUNT CREATION

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#17]
Epic: #2

As a **user** I can **create an account** so that **I can use the account to add content**.

### Acceptance Criteria: 

* A site user can create an account

### Tasks:

- [x] Install Django AllAuth
- [x] Add path to urls.py
- [x] Add AllAuth and redirects to settings.py
- [x] Adjust navigation links
- [x] Copy allauth templates to templates directory
- [x] Edit templates to match site
- [x] Successfully create a new user via the web pages
