### ISSUE TITLE
USER STORY: ADD COMMENTS TO EVENT

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#18]
Epic: #4 

As a **user** I can **add comments to an event when logged in** so that **I can add comments to an event**.

### Acceptance Criteria: 

* A user can add a comment to an event when registered and logged in

### Tasks:

- [x] Import crispy forms
- [x] Add crispy template styles to settings.py
- [x] Add forms.py to Events app.
- [x] Import and display form in views.py
- [x] Display form in template
- [x] Add Post method to views.py
- [x] Add comments via the form
---
