### ISSUE TITLE
USER STORY: ATTEND EVENTS

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#19]
Epic: #4 

As a **user** I can **mark that I am attending an event** so that **I can show my interest in an event**.

### Acceptance Criteria: 

* User can click a button and see the number of attendees adjust and the icon change to reflect the status

### Tasks:

- [x] Create view in views.py
- [x] Modify event detail template to have button and changing icons via a form
- [x] Add new path to urls.py
---
