### ISSUE TITLE
USER STORY: MESSAGES

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#20]
Epic: #5 

As a **user** I can **see messages to let me know my action has been carried out** so that **I receive information about my actions**.

### Acceptance Criteria: 

* Message display when user logs in or logs out or registers an account.

### Tasks:

- [x] Import constants as messages from django.contrib.message in settings.py
- [x] Add tags to settings.py
- [x] Add messages to base.html
- [x] Add javascript set timeout function to dismiss alerts in base.html
- [x] Test functionality
---
