### ISSUE TITLE
USER STORY: ADD EVENT

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#21]
Epic: #4 

As a **registered user** I can **add an event** so that **I can list my event on the site**.

### Acceptance Criteria: 

* User can add an event via an add_event form

### Tasks:

- [x] Create template for add_event page
- [x] Add Event form to forms.py
- [x] Add url to urls.py
- [x] Add addeventview to views.py
- [x] Test functionality by creating an event with an image
---
