### ISSUE TITLE
USER STORY: EDIT EVENT

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#22]
Epic: #4

As a **registered user** I can **edit my own event** so that **I can correct mistakes and update details**.

### Acceptance Criteria: 
User can edit their events

### Tasks:

- [x] Create edit_event template
- [x] Add path to urls.py
- [x] Add links to events and event_detail templates
- [x] Add get_success_url to redirect after pressing button on form
- [x] Test that the edit event form loads and user can edit the event.
---
