### ISSUE TITLE
USER STORY: DELETE EVENT

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#23]
Epic: #4

As a **registered user** I can **delete my events** so that **remove my events from the site**.

### Acceptance Criteria: 

* User is able to delete their event

### Tasks:

- [x] Create delete_event template
- [x] Add DeleteEventView class to views.py
- [x] Add path to urls.py
- [x] Add delete links to events and event detail pages
- [x] Test delete function
---
