### ISSUE TITLE
USER STORY: RESTRICT PERMISSIONS

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#25]
Epic: #4 

As an **event organiser** I can **prevent others from editing or deleting my events** so that **my events are not edited or deleted by other users**.

### Acceptance Criteria: 

* Users can only see links to edit or delete on events that they organised and others receive a 403 Forbidden Page or are directed to the login page if not registered and logged in, when accessing the links directly.

### Tasks:

- [x] Add Login Required to templates to hide links from users who did not organise the event
- [x] Add LoginRequiredMixin to Add Event, Edit Event and Delete Event views.
- [x] Add UserPassesTestMixin to Edit Event and Delete Event views.
- [x] Test that edit and delete links are hidden for events the user did not create.
- [x] Access event /delete and /edit urls to check that 403 Pages load or that the user is required to login if not logged in.
---
