### ISSUE TITLE
USER STORY: COMMENT SUCCESSFUL INDICATOR

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#26]
Epic: #4

As a **user** I can **view an alert** so that **I know that my comment is awaiting approval**.

### Acceptance Criteria: 

* When a user enter a comment, they will see a message telling them their comment is waiting for approval.

### Tasks:

- [x] Add if statement to event details template to check if there is a comment waiting for approval and the current user is the author of the comment and display an information text.
- [x] Import messages to views.py
- [x] Add alert to Event Detail view to display to user
- [x] Test functionality by creating a new comment
---
