### ISSUE TITLE
USER STORY: DESIGN

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#29]
Epic: #5

As a **user** I can **want the site to be responsive** so that **I can view on different devices**.

### Acceptance Criteria: 

* Site responds to different widths in browser and works on different screen sizes.

### Tasks:

- [x] Install Bootstrap
- [x] Create media viewpoint
- [x] Test with Chrome Dev Tools for responsiveness
- [x] Test on different devices
---
