### ISSUE TITLE
USER STORY: ADMIN PANEL CUSTOMISATION

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#7]
Epic: #1

As a **site administrator** I can **use the admin panel to filter and search content and use a WYSIWYG editor and auto-generate slugs** so that **I can easily add and manage content**.

### Acceptance Criteria: 

* WYSIWYG Editor displays in Admin Panel, search and filter fields are visible, slug fields auto-generate.

### Tasks:

- [x] Install and add Summernote
- [x] Add filters and searches
- [x] Add slugfield auto-generation
---
