### ISSUE TITLE
USER STORY: ADD IMAGES TO EVENTS IN ADMIN PANEL

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#8]
Epic #1 

As an **admin** I can **add images in the admin panel** so that **I can add images to events**.

### Acceptance Criteria: 

* Administrator can add images to new events without errors.

### Tasks:

- [x] Install Cloudinary
- [x] Add API to env.py
- [x] Add Cloudinary to settings.py
- [x] Test by creating event with image
---
