### ISSUE TITLE
USER STORY: VIEW A HOME PAGE

### ISSUE THREAD

**Issue by broken-helix** [broken-helix/keep-it-tidy-london#9]
Epic #3

As a **user** I can **view a home page** so that **I can understand what the site is about**.

### Acceptance Criteria: 

* The site loads a home page.

### Tasks:

- [x] Connect project urls.py to app urls.py
- [x] Create app urls.py
- [x] Add app template folder and index.html file
- [x] Add index.html to views.py
---
